### PR TITLE
Modify serialization strategy for tool results

### LINKED ISSUE #230: Ability to return images from Anthropic tool calls
Uniquely(?), Anthropic API lets your tool call results contain images. This is different than just having tool call results that happen to include data URIs; if Anthropic doesn't "know" that it's looking at an image, you will:

1. Use 100X more tokens than it should, like tens of thousands of tokens for a simple 640x480 plot instead of a mere 600 or so.
2. Get completely hallucinated results as Anthropic can't decode the image, but it will somehow imagine it can.

The big question to me is how Anthropic tools should indicate that they're returning content lists, not a JSON string.

This is one way: use an explicit `I()` to say "I'm giving you a raw JSONifiable value, don't treat it as a string". With this style, a simple two-line change in the `tool_string` function is all that's needed to support this (`if (inherits(x@value, "AsIs")) { x@value }`). This wouldn't even be specific to Anthropic, you could do this anytime you want a tool call not to mess with your return value.

```r
library(elmer)
library(promises)

options(elmer_verbosity = 2)

chat <- chat_claude(model = "claude-3-5-sonnet-latest")

get_picture <- function() {
  image_path <- system.file("help/figures/pch.png", package = "graphics")
  bytes <- readBin(image_path, "raw", n = file.info(image_path)$size)
  list(
    list(
      type = "image",
      source = list(
        type = "base64",
        media_type = "image/png",
        data = base64enc::base64encode(bytes)
      )
    )
  ) |> I()
}

chat$register_tool(tool(
  get_picture,
  "Returns an image"
))

chat$stream("What do you see in the picture from the tool?") |>
  coro::collect() |>
  unlist() |>
  paste(collapse = "") |>
  cat()
```

Option 2 would be similar except that the tool would return a list of proper `ContentXXX` objects:

```r
get_picture <- function() {
  image_path <- system.file("help/figures/pch.png", package = "graphics")
  bytes <- readBin(image_path, "raw", n = file.info(image_path)$size)
  list(
    ContentImageInline(
      type = "image/png",
      data = base64enc::base64encode(bytes)
    )
  )
}
```

This is a nicer function for the user, but we'd need to add code to elmer so that in Anthropic mode only, it knows to look for lists of pure Content and treat it differently. On the plus side, if other providers started supporting images in tool results, with this option you could write tools in a portable way.

### PR DESCRIPTION
**Pull request by jcheng5**
Closes #230 

### Update 2024-12-18 14:25 PST

This went from a very targeted "Add `I()` to a tool result to prevent it from being double JSON encoded" to changing the default serialization strategy for tool call responses.

The previous behavior only really made sense if you returned a single-element character vector or the output of `jsonlite::toJSON()`; these work the same way in the new code. But the new code also makes sense for multi-element character vectors (collapses them with `"\n"`) and for JSON-serializable objects (they are automatically serialized), in addition to `I()`.

### CODE REVIEW

**Comment by hadley** [comment]
This seems reasonable to me, even if we do eventually end up adding a specific image content type. Will just need some docs.

**Comment by jcheng5** [comment]
I'm a little surprised that `tool_string` calls `toString(x@value)` instead of `jsonlite::toJSON(x@value, auto_unbox = TRUE)`.

For example, if you return a data frame:

```r
> toString(cars)
[1] "c(4, 4, 7, 7, 8, 9, 10, 10, 10, 11, 11, 12, 12, 12, 12, 13, 13, 13, 13, 14, 14, 14, 14, 15, 15, 15, 16, 16, 17, 17, 17, 18, 18, 18, 18, 19, 19, 19, 20, 20, 20, 20, 20, 22, 23, 24, 24, 24, 24, 25), c(2, 10, 4, 22, 16, 10, 18, 26, 34, 17, 28, 14, 20, 24, 28, 26, 34, 34, 46, 26, 36, 60, 80, 20, 26, 54, 32, 40, 32, 40, 50, 42, 56, 76, 84, 36, 46, 68, 32, 48, 52, 56, 64, 66, 54, 70, 92, 93, 120, 85)"
> jsonlite::toJSON(cars, auto_unbox = TRUE)
[{"speed":4,"dist":2},{"speed":4,"dist":10},{"speed":7,"dist":4},{"speed":7,"dist":22},{"speed":8,"dist":16},{"speed":9,"dist":10},{"speed":10,"dist":18},{"speed":10,"dist":26},{"speed":10,"dist":34},{"speed":11,"dist":17},{"speed":11,"dist":28},{"speed":12,"dist":14},{"speed":12,"dist":20},{"speed":12,"dist":24},{"speed":12,"dist":28},{"speed":13,"dist":26},{"speed":13,"dist":34},{"speed":13,"dist":34},{"speed":13,"dist":46},{"speed":14,"dist":26},{"speed":14,"dist":36},{"speed":14,"dist":60},{"speed":14,"dist":80},{"speed":15,"dist":20},{"speed":15,"dist":26},{"speed":15,"dist":54},{"speed":16,"dist":32},{"speed":16,"dist":40},{"speed":17,"dist":32},{"speed":17,"dist":40},{"speed":17,"dist":50},{"speed":18,"dist":42},{"speed":18,"dist":56},{"speed":18,"dist":76},{"speed":18,"dist":84},{"speed":19,"dist":36},{"speed":19,"dist":46},{"speed":19,"dist":68},{"speed":20,"dist":32},{"speed":20,"dist":48},{"speed":20,"dist":52},{"speed":20,"dist":56},{"speed":20,"dist":64},{"speed":22,"dist":66},{"speed":23,"dist":54},{"speed":24,"dist":70},{"speed":24,"dist":92},{"speed":24,"dist":93},{"speed":24,"dist":120},{"speed":25,"dist":85}] 
```

**Comment by jcheng5** [comment]
This could potentially be a parameter on `tool()`: `serialize = c("json", "string", "as-is")`

**Comment by hadley** [comment]
You should just change to that if you think it makes sense (and it doesn't make the tests break). I don't think I really thought through that decision at all.

**Comment by jcheng5** [comment]
I pushed a change so the logic in `tool_string` is now:

1. If you return a string, that's passed as-is to the model. (E.g., `"The time is 1:20pm"` becomes `"content": "The time is 1:20pm"`)
2. If you return JSON (`inherits(x@value, "json")`), then that becomes the content, with one more level of stringifying: `jsonlite::toJSON(list(h=13, m=20), auto_unbox = TRUE)` becomes `"content": "{\"h\":13,\"m\":20}"`. This is the common case.
3. If you return `AsIs`, we attach it verbatim to the message and it only gets serialized with the rest of the message. So `I(list(h=13, m=20))` would become `"content": {"h": 13, "m": 20}`.

**Pull request merged**
